### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by DaveTryon** [TestStack/uia-custom-pattern-managed#2]
@ivan-danilov, I'd love to try to leverage some of your work here, but it's off-limits to our team without some sort of license. Can I ask you to put this under a permissive license, possibly an MIT license? Thanks!

**Comment by ivan-danilov** [comment]
Added the file. It was written before GitHub started to suggest adding a license to every new repo, just forgot. My team had used it successfully for a few purposes, so if you'll get stuck somewhere - feel free to ask. I see that the original posts of Michael Bernstein no longer available... which makes some parts not very intuitive, to say the least.

**Comment by DaveTryon** [comment]
👍
